/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDepositRouteImport } from './routes/_authenticated/deposit'
import { Route as AuthenticatedInvestRouteImport } from './routes/_authenticated/invest'
import { Route as AuthenticatedKycRouteImport } from './routes/_authenticated/kyc'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedSwapRouteImport } from './routes/_authenticated/swap'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin/support'
import { Route as AuthenticatedMarketIndexRouteImport } from './routes/_authenticated/market.index'
import { Route as AuthenticatedMarketSymbolRouteImport } from './routes/_authenticated/market.$symbol'
import { Route as AuthenticatedSupportIndexRouteImport } from './routes/_authenticated/support/index'
import { Route as AuthenticatedSupportTicketIdRouteImport } from './routes/_authenticated/support/$ticketId'
import { Route as AuthenticatedAdminSupportTicketIdRouteImport } from './routes/_authenticated/admin/support/$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDepositRoute = AuthenticatedDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestRoute = AuthenticatedInvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKycRoute = AuthenticatedKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSwapRoute = AuthenticatedSwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/admin/support',
    path: '/admin/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketIndexRoute =
  AuthenticatedMarketIndexRouteImport.update({
    id: '/market/',
    path: '/market/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketSymbolRoute =
  AuthenticatedMarketSymbolRouteImport.update({
    id: '/market/$symbol',
    path: '/market/$symbol',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupportIndexRoute =
  AuthenticatedSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupportTicketIdRoute =
  AuthenticatedSupportTicketIdRouteImport.update({
    id: '/support/$ticketId',
    path: '/support/$ticketId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSupportTicketIdRoute =
  AuthenticatedAdminSupportTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => AuthenticatedAdminSupportRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/invest': typeof AuthenticatedInvestRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/swap': typeof AuthenticatedSwapRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/support': typeof AuthenticatedAdminSupportRouteWithChildren
  '/market/$symbol': typeof AuthenticatedMarketSymbolRoute
  '/support/$ticketId': typeof AuthenticatedSupportTicketIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/market/': typeof AuthenticatedMarketIndexRoute
  '/support/': typeof AuthenticatedSupportIndexRoute
  '/admin/support/$ticketId': typeof AuthenticatedAdminSupportTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/invest': typeof AuthenticatedInvestRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/swap': typeof AuthenticatedSwapRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/support': typeof AuthenticatedAdminSupportRouteWithChildren
  '/market/$symbol': typeof AuthenticatedMarketSymbolRoute
  '/support/$ticketId': typeof AuthenticatedSupportTicketIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/market': typeof AuthenticatedMarketIndexRoute
  '/support': typeof AuthenticatedSupportIndexRoute
  '/admin/support/$ticketId': typeof AuthenticatedAdminSupportTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/deposit': typeof AuthenticatedDepositRoute
  '/_authenticated/invest': typeof AuthenticatedInvestRoute
  '/_authenticated/kyc': typeof AuthenticatedKycRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/swap': typeof AuthenticatedSwapRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRouteWithChildren
  '/_authenticated/market/$symbol': typeof AuthenticatedMarketSymbolRoute
  '/_authenticated/support/$ticketId': typeof AuthenticatedSupportTicketIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/market/': typeof AuthenticatedMarketIndexRoute
  '/_authenticated/support/': typeof AuthenticatedSupportIndexRoute
  '/_authenticated/admin/support/$ticketId': typeof AuthenticatedAdminSupportTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/deposit'
    | '/invest'
    | '/kyc'
    | '/portfolio'
    | '/referrals'
    | '/swap'
    | '/wallet'
    | '/withdraw'
    | '/admin/support'
    | '/market/$symbol'
    | '/support/$ticketId'
    | '/admin/'
    | '/market/'
    | '/support/'
    | '/admin/support/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/deposit'
    | '/invest'
    | '/kyc'
    | '/portfolio'
    | '/referrals'
    | '/swap'
    | '/wallet'
    | '/withdraw'
    | '/admin/support'
    | '/market/$symbol'
    | '/support/$ticketId'
    | '/admin'
    | '/market'
    | '/support'
    | '/admin/support/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/deposit'
    | '/_authenticated/invest'
    | '/_authenticated/kyc'
    | '/_authenticated/portfolio'
    | '/_authenticated/referrals'
    | '/_authenticated/swap'
    | '/_authenticated/wallet'
    | '/_authenticated/withdraw'
    | '/_authenticated/admin/support'
    | '/_authenticated/market/$symbol'
    | '/_authenticated/support/$ticketId'
    | '/_authenticated/admin/'
    | '/_authenticated/market/'
    | '/_authenticated/support/'
    | '/_authenticated/admin/support/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/deposit': {
      id: '/_authenticated/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof AuthenticatedDepositRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invest': {
      id: '/_authenticated/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof AuthenticatedInvestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kyc': {
      id: '/_authenticated/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthenticatedKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/swap': {
      id: '/_authenticated/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof AuthenticatedSwapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market/': {
      id: '/_authenticated/market/'
      path: '/market'
      fullPath: '/market/'
      preLoaderRoute: typeof AuthenticatedMarketIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market/$symbol': {
      id: '/_authenticated/market/$symbol'
      path: '/market/$symbol'
      fullPath: '/market/$symbol'
      preLoaderRoute: typeof AuthenticatedMarketSymbolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support/': {
      id: '/_authenticated/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof AuthenticatedSupportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support/$ticketId': {
      id: '/_authenticated/support/$ticketId'
      path: '/support/$ticketId'
      fullPath: '/support/$ticketId'
      preLoaderRoute: typeof AuthenticatedSupportTicketIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/support/$ticketId': {
      id: '/_authenticated/admin/support/$ticketId'
      path: '/$ticketId'
      fullPath: '/admin/support/$ticketId'
      preLoaderRoute: typeof AuthenticatedAdminSupportTicketIdRouteImport
      parentRoute: typeof AuthenticatedAdminSupportRoute
    }
  }
}

interface AuthenticatedAdminSupportRouteChildren {
  AuthenticatedAdminSupportTicketIdRoute: typeof AuthenticatedAdminSupportTicketIdRoute
}

const AuthenticatedAdminSupportRouteChildren: AuthenticatedAdminSupportRouteChildren =
  {
    AuthenticatedAdminSupportTicketIdRoute:
      AuthenticatedAdminSupportTicketIdRoute,
  }

const AuthenticatedAdminSupportRouteWithChildren =
  AuthenticatedAdminSupportRoute._addFileChildren(
    AuthenticatedAdminSupportRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDepositRoute: typeof AuthenticatedDepositRoute
  AuthenticatedInvestRoute: typeof AuthenticatedInvestRoute
  AuthenticatedKycRoute: typeof AuthenticatedKycRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedSwapRoute: typeof AuthenticatedSwapRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRouteWithChildren
  AuthenticatedMarketSymbolRoute: typeof AuthenticatedMarketSymbolRoute
  AuthenticatedSupportTicketIdRoute: typeof AuthenticatedSupportTicketIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedMarketIndexRoute: typeof AuthenticatedMarketIndexRoute
  AuthenticatedSupportIndexRoute: typeof AuthenticatedSupportIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDepositRoute: AuthenticatedDepositRoute,
  AuthenticatedInvestRoute: AuthenticatedInvestRoute,
  AuthenticatedKycRoute: AuthenticatedKycRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedSwapRoute: AuthenticatedSwapRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRouteWithChildren,
  AuthenticatedMarketSymbolRoute: AuthenticatedMarketSymbolRoute,
  AuthenticatedSupportTicketIdRoute: AuthenticatedSupportTicketIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedMarketIndexRoute: AuthenticatedMarketIndexRoute,
  AuthenticatedSupportIndexRoute: AuthenticatedSupportIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
