/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedMarketIndexRouteImport } from './routes/_authenticated/market.index'
import { Route as AuthenticatedMarketSymbolRouteImport } from './routes/_authenticated/market.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketIndexRoute =
  AuthenticatedMarketIndexRouteImport.update({
    id: '/market/',
    path: '/market/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketSymbolRoute =
  AuthenticatedMarketSymbolRouteImport.update({
    id: '/market/$symbol',
    path: '/market/$symbol',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/market/$symbol': typeof AuthenticatedMarketSymbolRoute
  '/market/': typeof AuthenticatedMarketIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/market/$symbol': typeof AuthenticatedMarketSymbolRoute
  '/market': typeof AuthenticatedMarketIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/market/$symbol': typeof AuthenticatedMarketSymbolRoute
  '/_authenticated/market/': typeof AuthenticatedMarketIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/wallet' | '/market/$symbol' | '/market/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/wallet' | '/market/$symbol' | '/market'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/wallet'
    | '/_authenticated/market/$symbol'
    | '/_authenticated/market/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market/': {
      id: '/_authenticated/market/'
      path: '/market'
      fullPath: '/market/'
      preLoaderRoute: typeof AuthenticatedMarketIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market/$symbol': {
      id: '/_authenticated/market/$symbol'
      path: '/market/$symbol'
      fullPath: '/market/$symbol'
      preLoaderRoute: typeof AuthenticatedMarketSymbolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedMarketSymbolRoute: typeof AuthenticatedMarketSymbolRoute
  AuthenticatedMarketIndexRoute: typeof AuthenticatedMarketIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedMarketSymbolRoute: AuthenticatedMarketSymbolRoute,
  AuthenticatedMarketIndexRoute: AuthenticatedMarketIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
